[[constraint]]
    name="github.com/rs/zerolog"
    version="v1.8.0"

[[constraint]]
    name="github.com/spf13/cobra"
    version="v0.0.3"

[[constraint]]
    name="github.com/nalej/derrors"
    version="v2.1.0"

[[constraint]]
    name="github.com/nalej/grpc-utils"
    version="v1.5.0"

[[constraint]]
    name="github.com/nalej/grpc-common-go"
    version="=v0.0.38"

[[constraint]]
    name="github.com/nalej/grpc-provisioner-go"
    version="=v0.0.11"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[[constraint]]
    name="github.com/onsi/ginkgo"
    version="v1.6.0"

[[constraint]]
    name="github.com/onsi/gomega"
    version="v1.4.2"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/tidwall/gjson"
  version = "v1.1.4"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "=v33.4.0"

##
## Kubernetes dependencies
##

[[constraint]]
    name="k8s.io/client-go"
    version="v9.0.0"

[[constraint]]
    name = "k8s.io/api"
    version="kubernetes-1.12.0"

[[constraint]]
   name = "k8s.io/apimachinery"
   version="kubernetes-1.12.0"

[[override]]
   name = "k8s.io/apiextensions-apiserver"
   version="kubernetes-1.12.0"

[[override]]
   name = "k8s.io/apiserver"
   version="kubernetes-1.12.0"

[[override]]
   name = "k8s.io/cli-runtime"
   version="kubernetes-1.12.0"

# Fix vendor/k8s.io/kubernetes/pkg/kubectl/cmd/templates/markdown.go:30:5: cannot use ASCIIRenderer literal (type *ASCIIRenderer) as type blackfriday.Renderer in assignment:
[[override]]
  name = "github.com/russross/blackfriday"
  revision = "300106c228d52c8941d4b3de6054a6062a86dda3"

# Fix vendor/k8s.io/kubernetes/pkg/util/parsers/parsers.go:36:16: undefined: reference.ParseNormalizedNamed
[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"
