###
# Application example
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: provisioner
  name: provisioner
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: provisioner
  template:
    metadata:
      labels:
        cluster: management
        component: provisioner
    spec:
      containers:
      - name: provisioner
        image: __NPH_REGISTRY/__NPH_REGISTRY_NAMESPACE/provisioner:__NPH_VERSION
        imagePullPolicy: Always
        volumeMounts:
        - name: temp-dir
          mountPath: "/tmp/nalej"
        args:
          - "run"
          - "--debug"
          - "--tempPath=/tmp/nalej/"
        securityContext:
          runAsUser: 2000
      volumes:
        - name: temp-dir
          emptyDir: {}
      imagePullSecrets:
      - name: nalej-registry
